id: "0x0100"
name: Shade Configuration
description: The shade configuration cluster provides an interface for reading information
    about a shade, and configuring its open and closed limits.
server:
    attr:
    - id: "0x0000"
        name: Physical Closed Limit
        type: u16
        access: r
        required: o
    - id: "0x0001"
        name: MotorStepSize
        type: u8
        access: r
        required: o
    - id: "0x0002"
        name: Status
        type: bmp8
        access: rw
        required: m
        bits:
            "0": Shade operational
            "1": Shade adjusting
            "2": Shade direction
            "3": Direction Reversed
    - id: "0x0010"
        name: Closed Limit
        type: u16
        access: rw
        default: "0x0001"
        required: m
        range: 0x0001,0xfffe
    - id: "0x0011"
        name: Mode
        type: enum8
        access: rw
        default: "0x00"
        required: m
        values:
            "0x00": Normal
            "0x01": Configure
            "0xFF": Invalid
client: {}
