# Status: Done
id: "0x0001"
name: Power Configuration
description: Attributes for determining more detailed information about a device’s
    power source(s), and for configuring under/over voltage alarms.
server:
    attr:
      - id: "0x0000"
        name: Mains Voltage
        type: u16
        unit: Volts
        multiplier: 10
        access: r
      - id: "0x0001"
        name: Mains Frequency
        description: |
            Resolution of 2Hz
            Special values:
            * 0x00 frequency too low to measure
            * 0xfe frequency too high to measure
            * 0xff unable to measure
        type: u8
        unit: Hertz
        multiplier: 2
        range: "0x01,0xfd"
        access: r
      - id: "0x0010"
        name: Mains Alarm Mask
        type: bmp8
        access: rw
        default: "0x00"
        bits:
            "0": Mains Voltage too low
            "1": Mains Voltage too high
            "2": Mains power supply lost/unavailable
      - id: "0x0011"
        name: Mains Voltage Min Threshold
        type: u16
        access: rw
        unit: Volts
        multiplier: 10
        default: "0"
      - id: "0x0012"
        name: Mains Voltage Max Threshold
        type: u16
        access: rw
        unit: Volts
        multiplier: 10
        default: "0xffff"
      - id: "0x0013"
        name: Mains Voltage Dwell Trip Point
        description: |
          Length of time that the value of MainsVoltage MAY exist beyond either
          of its thresholds before an alarm is generated
        type: u16
        access: rw
        unit: Seconds
        default: "0x0000"
      - id: "0x0020"
        name: Battery Voltage
        type: u8
        unit: Volts
        multiplier: 10
        access: r
      - id: "0x0021"
        name: Battery Percentage Remaining
        type: u8
        report: true
        unit: Percent
        multiplier: 2
        range: "0x00,0xC8"
        access: r
      - id: "0x0030"
        name: Battery Manufacturer
        type: cstring
        access: rw
        range: 0,16
      - id: "0x0031"
        name: Battery Size
        type: enum8
        access: rw
        default: 0xff
        values:
            "0x00": No Battery
            "0x01": Built in
            "0x02": Other
            "0x03": AA
            "0x04": AAA
            "0x05": C
            "0x06": D
            "0x07": CR2
            "0x08": CR123A
            "0xFF": Unknown
      - id: "0x0032"
        name: Battery AHr Rating
        type: u16
        unit: MilliAmpereHours
        multiplier: 0.1
        access: rw
      - id: "0x0033"
        name: Battery Quantity
        type: u8
        access: rw
      - id: "0x0034"
        name: Battery Rated Voltage
        type: u8
        unit: Volts
        multiplier: 10
        access: rw
      - id: "0x0035"
        name: Battery Alarm Mask
        type: bmp8
        access: rw
        default: "0x00"
        bits:
            "0": Battery Voltage too low
            "1": Battery Alarm 1
            "2": Battery Alarm 2
            "3": Battery Alarm 3
      - id: "0x0036"
        name: Battery Voltage Min Threshold
        type: u8
        access: rw
        unit: Volts
        multiplier: 10
        default: "0x00"
      - id: "0x0037"
        name: Battery Voltage Threshold 1
        type: u8
        access: rw
        unit: Volts
        multiplier: 10
        default: "0x00"
      - id: "0x0038"
        name: Battery Voltage Threshold 2
        type: u8
        access: rw
        unit: Volts
        multiplier: 10
        default: "0x00"
      - id: "0x0039"
        name: Battery Voltage Threshold 3
        type: u8
        access: rw
        unit: Volts
        multiplier: 10
        default: "0x00"
      - id: "0x003a"
        name: Battery Percentage Min Threshold
        type: u8
        access: rw
        unit: Percent
        multiplier: 2
        range: "0x00,0xC8"
      - id: "0x003b"
        name: Battery Percentage Threshold 1
        type: u8
        access: rw
        unit: Percent
        multiplier: 2
        range: "0x00,0xC8"
      - id: "0x003c"
        name: Battery Percentage Threshold 2
        type: u8
        access: rw
        unit: Percent
        multiplier: 2
        range: "0x00,0xC8"
      - id: "0x003d"
        name: Battery Percentage Threshold 3
        type: u8
        access: rw
        unit: Percent
        multiplier: 2
        range: "0x00,0xC8"
      - id: "0x003E"
        name: Battery Alarm State
        type: bmp32
        access: rw
        default: "0"
        bits:
            "0": Minimum Threshold 1 for Voltage or Percentage reached for Battery Source 1
            "1": Threshold 1 for Voltage or Percentage reached for Battery Source 1
            "2": Threshold 2 for Voltage or Percentage reached for Battery Source 1
            "3": Threshold 3 for Voltage or Percentage reached for Battery Source 1
            "10": Minimum Threshold 1 for Voltage or Percentage reached for Battery Source 2
            "11": Threshold 1 for Voltage or Percentage reached for Battery Source 2
            "12": Threshold 2 for Voltage or Percentage reached for Battery Source 2
            "13": Threshold 3 for Voltage or Percentage reached for Battery Source 2
            "20": Minimum Threshold 1 for Voltage or Percentage reached for Battery Source 3
            "21": Threshold 1 for Voltage or Percentage reached for Battery Source 3
            "22": Threshold 2 for Voltage or Percentage reached for Battery Source 3
            "23": Threshold 3 for Voltage or Percentage reached for Battery Source 3
            "30": Mains power lost/unavailable
client: {}
