# Status: Done
id: "0x0002"
name: Device Temperature Configuration
description: Attributes for determining information about a device’s internal temperature,
    and for configuring under/over temperature alarms.
server:
    attr:
      - id: "0x0000"
        name: Current Temperature
        type: s16
        range: -200,200
        unit: DegreesCelsius
        access: r
        require: true
      - id: "0x0001"
        name: Min Temp Experienced
        type: s16
        range: -200,200
        unit: DegreesCelsius
        access: r
      - id: "0x0002"
        name: Max Temp Experienced
        type: s16
        range: -200,200
        unit: DegreesCelsius
        access: r
      - id: "0x0003"
        name: Over Temp Total Dwell
        description: Total time the device has spent above the tmperature specified by High Temp Threshold
        type: u16
        units: Hr
        invalid: 0xffff
      - id: "0x0010"
        name: Device Temp Alarm Mask
        type: bmp8
        access: rw
        bits:
            "0": Temperature too low
            "1": Temperature too high
      - id: "0x0011"
        name: Low Temp Threshold
        description: |
            If the current temperature drops below the threshold for longer
            than the time specified by low temp dwell, an alarm will be triggered
        type: s16
        range: -200,200
        unit: DegreesCelsius
        access: rw
      - id: "0x0012"
        name: High Temp Threshold
        description: |
            If the current temperature goes above the threshold for longer
            than the time specified by high temp dwell, an alarm will be triggered
        type: s16
        range: -200,200
        unit: DegreesCelsius
        access: rw
      - id: "0x0013"
        name: Low Temp Dwell Trip Point
        unit: Seconds
        type: u24
      - id: "0x0014"
        name: High Temp Dwell Trip Point
        unit: Seconds
        type: u24
client: {}
