id: "0x0007"
name: On/Off Switch Configuration
description: Attributes and commands for configuring On/Off switching devices
server:
    attr:
    - id: "0x0000"
        name: SwitchType
        description: The SwitchType attribute specifies the basic functionality of
            the On/Off switching device.
        type: enum8
        access: r
        default: "0"
        required: true
        values:
            "0x00": Toggle
            "0x01": Momentary
    - id: "0x0010"
        name: SwitchActions
        description: The SwitchActions attribute is 8-bits in length and specifies
            the commands of the On/Off cluster to be generated when the switch moves
            between its two states.
        type: enum8
        access: rw
        default: "0"
        required: true
        values:
            "0x00": On-Off
            "0x01": Off-On
            "0x02": Toggle
client: {}
