id: "0x0301"
name: Ballast Configuration
description: Attributes and commands to configure a ballast.
server:
    attr:
      - id: "0x0000"
        name: Physical Min Level
        description: |
          It specifies the minimum light level the ballast can achieve. It is
          specified in the range 0x01 to 0xfe, and specifies the light output
          of the ballast according to the dimming light curve
        type: u8
        access: r
        default: "0x01"
        range: 0x01,0xfe
      - id: "0x0001"
        name: Physical Max Level
        description: |
          It specifies the maximum light level the ballast can achieve. It is
          specified in the range 0x01 to 0xfe, and specifies the light output
          of the ballast according to the dimming light curve
        type: u8
        access: r
        default: "0xfe"
        range: 0x01,0xfe
      - id: "0x0002"
        name: Ballast Status
        description: |
          It specifies the activity status of the ballast functions. Where a
          function is active, the corresponding bit is 1. Where a function is
          not active, the corresponding bit is 0. This means that bit 0 with
          a value of 0 means the ballast is operational and bit 1 with a
          value of 0 that the lamp(s) is/are in their socket(s)
        type: bmp8
        access: r
        default: "0x00"
        required: true
        range: 0x00,0x03
        bits:
            0: Non-operational
            1: Lamp not in socket
      - id: "0x0010"
        name: Min Level
        description: |
          It specifies the minimum light level the ballast is permitted to use.
          It is specified in the range 0x01 to 0xfe, and specifies the light
          output of the ballast according to the dimming light curve. The value
          is both greater than or equal to PhysicalMinLevel and less than or equal
          to MaxLevel
        type: u8
        access: rw
        default: "0x01"
        range: 0x01,0xfe
      - id: "0x0011"
        name: Max Level
        description: |
          It specifies the maximum light level the ballast is permitted to use.
          It is specified in the range 0x01 to 0xfe, and specifies the light
          output of the ballast according to the dimming light curve. The value
          is both less than or equal to PhysicalMaxLevel and greater than or equal
          to MinLevel
        type: u8
        access: rw
        default: "0xfe"
        range: 0x01,0xfe
      - id: "0x0012"
        name: Power On Level
        description: |
          It specifies the light level to which the ballast will go when power
          is applied (e.g., when mains power is re-established after a power
          failure). It can have a value between 0x00 and 0xfe to set it to
          a specific light level, according to the dimming light curve, or
          0xff to set it to the value it was before the power failure
        type: u8
        access: rw
        default: "0xfe"
        range: 0x00,0xfe
      - id: "0x0013"
        name: Power On Fade Time
        description: |
          Is the length of time, in tenths of a second, that the ballast takes to
          move to the light level specified in PowerOnLevel when power is applied
          (e.g., when mains power is re-established after a power failure).
        type: u16
        access: rw
        default: "0x0000"
        range: 0x0000,0xfffe
        unit: Seconds
        multiplier: 10
      - id: "0x0014"
        name: Intrinsic Ballast Factor
        description: |
          It specifies, as a percentage, the ballast factor of the ballast/lamp
          combination, prior to any adjustment.
        type: u8
        access: rw
        range: 0x00,0xfe
        unit: Percent
      - id: "0x0015"
        name: Ballast Factor Adjustment
        description: |
          It specifies the multiplication factor, as a percentage, to be applied
          to the configured light output of the lamps. A typical usage of this
          mechanism is to compensate for reduction in efficiency over the lifetime
          of a lamp. The light output is given by
          Actual light output = configured light output x BallastFactorAdjustment / 100%
          The range for this attribute is manufacturer dependent
        type: u8
        access: rw
        default: "0xff"
        range: 0x64,0xff
        unit: Percent
      - id: "0x0020"
        name: Lamp Quantity
        description: |
          It specifies the number of lamps connected to this ballast
        type: u8
        access: r
        range: 0x00,0xfe
      - id: "0x0030"
        name: Lamp Type
        desrciption: |
          It specifies the type of lamps (including their wattage) connected
          to the ballast
        type: cstring
        access: rw
      - id: "0x0031"
        name: Lamp Manufacturer
        description: |
          It specifies the name of the manufacturer of the currently connected
          lamps.
        type: cstring
        access: rw
      - id: "0x0032"
        name: Lamp Rated Hours
        description: |
          It specifies the number of hours of use the lamps are rated for by
          the manufacturer
        type: u24
        access: rw
        default: "0xffffff"
        invalid: "0xffffff"
        range: 0x000000,0xfffffe
      - id: "0x0033"
        name: Lamp Burn Hours
        description: |
          It specifies the length of time, in hours, the currently connected
          lamps have been operated, cumulative since the last re-lamping. Burn
          hours are not accumulated if the lamps are off and are reset to 0
          when a lamp is changed
        type: u24
        access: rw
        default: "0x000000"
        invalid: "0x000000"
        range: 0x000000,0xfffffe
      - id: "0x0034"
        name: Lamp Alarm Mode
        description: |
          It specifies which attributes can cause an alarm notification to be
          generated
        type: bmp8
        access: rw
        default: "0x00"
        range: 0x00,0x03
        bits:
            0: Lamp Burn Hours
      - id: "0x0035"
        name: Lamp Burn Hours Trip Point
        description: |
          It specifies the number of hours the LampBurnHours attribute can
          reach before an alarm is generated
        type: u24
        access: rw
        default: "0xffffff"
        range: 0x000000,0xfffffe
client: {}
