package cluster

import (
	"hemtjan.st/zcl"
	"hemtjan.st/zcl/cluster/closures"
	"hemtjan.st/zcl/cluster/general"
	"hemtjan.st/zcl/cluster/hvac"
	"hemtjan.st/zcl/cluster/ias"
	"hemtjan.st/zcl/cluster/ikea"
	"hemtjan.st/zcl/cluster/lighting"
	"hemtjan.st/zcl/cluster/measurement"
	"hemtjan.st/zcl/cluster/otau"
	"hemtjan.st/zcl/cluster/smartenergy"
)

var Clusters = map[zcl.ClusterID]zcl.Cluster{
	closures.DoorLockID:                            closures.DoorLockCluster,
	closures.WindowCoveringID:                      closures.WindowCoveringCluster,
	general.AlarmsID:                               general.AlarmsCluster,
	general.AnalogInputID:                          general.AnalogInputCluster,
	general.AnalogOutputID:                         general.AnalogOutputCluster,
	general.AnalogValueID:                          general.AnalogValueCluster,
	general.BasicID:                                general.BasicCluster,
	general.BinaryInputID:                          general.BinaryInputCluster,
	general.BinaryOutputID:                         general.BinaryOutputCluster,
	general.BinaryValueID:                          general.BinaryValueCluster,
	general.DeviceTemperatureConfigurationID:       general.DeviceTemperatureConfigurationCluster,
	general.DiagnosticsID:                          general.DiagnosticsCluster,
	general.GroupsID:                               general.GroupsCluster,
	general.IdentifyID:                             general.IdentifyCluster,
	general.LevelControlID:                         general.LevelControlCluster,
	general.LocationID:                             general.LocationCluster,
	general.MeterIdentificationID:                  general.MeterIdentificationCluster,
	general.MultistateInputID:                      general.MultistateInputCluster,
	general.MultistateOutputID:                     general.MultistateOutputCluster,
	general.MultistateValueID:                      general.MultistateValueCluster,
	general.OnOffID:                                general.OnOffCluster,
	general.OnOffSwitchConfigurationID:             general.OnOffSwitchConfigurationCluster,
	general.PollControlID:                          general.PollControlCluster,
	general.PowerConfigurationID:                   general.PowerConfigurationCluster,
	general.ScenesID:                               general.ScenesCluster,
	general.TimeID:                                 general.TimeCluster,
	hvac.DehumidificationControlID:                 hvac.DehumidificationControlCluster,
	hvac.FanControlID:                              hvac.FanControlCluster,
	hvac.PumpConfigurationAndControlID:             hvac.PumpConfigurationAndControlCluster,
	hvac.ThermostatID:                              hvac.ThermostatCluster,
	hvac.ThermostatUiConfigurationID:               hvac.ThermostatUiConfigurationCluster,
	ias.IasZoneID:                                  ias.IasZoneCluster,
	ikea.IkeaAirQualityID:                          ikea.IkeaAirQualityCluster,
	lighting.BallastConfigurationID:                lighting.BallastConfigurationCluster,
	lighting.ColorControlID:                        lighting.ColorControlCluster,
	measurement.BromateMeasurementID:               measurement.BromateMeasurementCluster,
	measurement.BromodichloromethaneMeasurementID:  measurement.BromodichloromethaneMeasurementCluster,
	measurement.BromoformMeasurementID:             measurement.BromoformMeasurementCluster,
	measurement.CarbonDioxideMeasurementID:         measurement.CarbonDioxideMeasurementCluster,
	measurement.CarbonMonoxideMeasurementID:        measurement.CarbonMonoxideMeasurementCluster,
	measurement.ChloraminesMeasurementID:           measurement.ChloraminesMeasurementCluster,
	measurement.ChlorineMeasurementID:              measurement.ChlorineMeasurementCluster,
	measurement.ChlorodibromomethaneMeasurementID:  measurement.ChlorodibromomethaneMeasurementCluster,
	measurement.ChloroformMeasurementID:            measurement.ChloroformMeasurementCluster,
	measurement.CopperMeasurementID:                measurement.CopperMeasurementCluster,
	measurement.DissolvedOxygenMeasurementID:       measurement.DissolvedOxygenMeasurementCluster,
	measurement.ElectricalMeasurementID:            measurement.ElectricalMeasurementCluster,
	measurement.EthyleneMeasurementID:              measurement.EthyleneMeasurementCluster,
	measurement.EthyleneOxideMeasurementID:         measurement.EthyleneOxideMeasurementCluster,
	measurement.FecalColiformEColiMeasurementID:    measurement.FecalColiformEColiMeasurementCluster,
	measurement.FlowMeasurementID:                  measurement.FlowMeasurementCluster,
	measurement.FluorideMeasurementID:              measurement.FluorideMeasurementCluster,
	measurement.FormaldehydeMeasurementID:          measurement.FormaldehydeMeasurementCluster,
	measurement.HaloaceticAcidsMeasurementID:       measurement.HaloaceticAcidsMeasurementCluster,
	measurement.HydrogenMeasurementID:              measurement.HydrogenMeasurementCluster,
	measurement.HydrogenSulfideMeasurementID:       measurement.HydrogenSulfideMeasurementCluster,
	measurement.IlluminanceLevelSensingID:          measurement.IlluminanceLevelSensingCluster,
	measurement.IlluminanceMeasurementID:           measurement.IlluminanceMeasurementCluster,
	measurement.LeadMeasurementID:                  measurement.LeadMeasurementCluster,
	measurement.ManganeseMeasurementID:             measurement.ManganeseMeasurementCluster,
	measurement.NitricOxideMeasurementID:           measurement.NitricOxideMeasurementCluster,
	measurement.NitrogenDioxideMeasurementID:       measurement.NitrogenDioxideMeasurementCluster,
	measurement.OccupancySensingID:                 measurement.OccupancySensingCluster,
	measurement.OxygenMeasurementID:                measurement.OxygenMeasurementCluster,
	measurement.OzoneMeasurementID:                 measurement.OzoneMeasurementCluster,
	measurement.Pm25MeasurementID:                  measurement.Pm25MeasurementCluster,
	measurement.PressureMeasurementID:              measurement.PressureMeasurementCluster,
	measurement.RelativeHumidityMeasurementID:      measurement.RelativeHumidityMeasurementCluster,
	measurement.SodiumMeasurementID:                measurement.SodiumMeasurementCluster,
	measurement.SulfateMeasurementID:               measurement.SulfateMeasurementCluster,
	measurement.SulfurDioxideMeasurementID:         measurement.SulfurDioxideMeasurementCluster,
	measurement.TemperatureMeasurementID:           measurement.TemperatureMeasurementCluster,
	measurement.TotalColiformBacteriaMeasurementID: measurement.TotalColiformBacteriaMeasurementCluster,
	measurement.TotalTrihalomethanesMeasurementID:  measurement.TotalTrihalomethanesMeasurementCluster,
	measurement.TurbidityMeasurementID:             measurement.TurbidityMeasurementCluster,
	otau.OtauID:                                    otau.OtauCluster,
	smartenergy.MeteringID:                         smartenergy.MeteringCluster,
}
