// Attributes and commands to configure a ballast.
package lighting

import (
	"neotor.se/zcl"
)

// BallastConfiguration
const BallastConfigurationID zcl.ClusterID = 769

var BallastConfigurationCluster = zcl.Cluster{
	ServerCmd: map[zcl.CommandID]func() zcl.Command{},
	ClientCmd: map[zcl.CommandID]func() zcl.Command{},
	ServerAttr: map[zcl.AttrID]func() zcl.Attr{
		PhysicalMinLevelAttr:        func() zcl.Attr { return new(PhysicalMinLevel) },
		PhysicalMaxLevelAttr:        func() zcl.Attr { return new(PhysicalMaxLevel) },
		BallastStatusAttr:           func() zcl.Attr { return new(BallastStatus) },
		MinLevelAttr:                func() zcl.Attr { return new(MinLevel) },
		MaxLevelAttr:                func() zcl.Attr { return new(MaxLevel) },
		PowerOnLevelAttr:            func() zcl.Attr { return new(PowerOnLevel) },
		PowerOnFadeTimeAttr:         func() zcl.Attr { return new(PowerOnFadeTime) },
		IntrinsicBallastFactorAttr:  func() zcl.Attr { return new(IntrinsicBallastFactor) },
		BallastFactorAdjustmentAttr: func() zcl.Attr { return new(BallastFactorAdjustment) },
		LampQuantityAttr:            func() zcl.Attr { return new(LampQuantity) },
		LampTypeAttr:                func() zcl.Attr { return new(LampType) },
		LampManufacturerAttr:        func() zcl.Attr { return new(LampManufacturer) },
		LampRatedHoursAttr:          func() zcl.Attr { return new(LampRatedHours) },
		LampBurnHoursAttr:           func() zcl.Attr { return new(LampBurnHours) },
		LampAlarmModeAttr:           func() zcl.Attr { return new(LampAlarmMode) },
		LampBurnHoursTripPointAttr:  func() zcl.Attr { return new(LampBurnHoursTripPoint) },
	},
	ClientAttr: map[zcl.AttrID]func() zcl.Attr{},
	SceneAttr:  []zcl.AttrID{},
}

// PhysicalMinLevel is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the minimum light level the ballast can achieve. It is
// specified in the range 0x01 to 0xfe, and specifies the light output
// of the ballast according to the dimming light curve
type PhysicalMinLevel zcl.Zu8

const PhysicalMinLevelAttr zcl.AttrID = 0

func (a PhysicalMinLevel) ID() zcl.AttrID            { return PhysicalMinLevelAttr }
func (a PhysicalMinLevel) Cluster() zcl.ClusterID    { return BallastConfigurationID }
func (a *PhysicalMinLevel) Value() *PhysicalMinLevel { return a }
func (a PhysicalMinLevel) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *PhysicalMinLevel) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = PhysicalMinLevel(*nt)
	return br, err
}

func (a PhysicalMinLevel) Readable() bool   { return true }
func (a PhysicalMinLevel) Writable() bool   { return false }
func (a PhysicalMinLevel) Reportable() bool { return false }
func (a PhysicalMinLevel) SceneIndex() int  { return -1 }

func (a PhysicalMinLevel) String() string {
	return zcl.Sprintf("%v", zcl.Zu8(a))
}

// PhysicalMaxLevel is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the maximum light level the ballast can achieve. It is
// specified in the range 0x01 to 0xfe, and specifies the light output
// of the ballast according to the dimming light curve
type PhysicalMaxLevel zcl.Zu8

const PhysicalMaxLevelAttr zcl.AttrID = 1

func (a PhysicalMaxLevel) ID() zcl.AttrID            { return PhysicalMaxLevelAttr }
func (a PhysicalMaxLevel) Cluster() zcl.ClusterID    { return BallastConfigurationID }
func (a *PhysicalMaxLevel) Value() *PhysicalMaxLevel { return a }
func (a PhysicalMaxLevel) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *PhysicalMaxLevel) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = PhysicalMaxLevel(*nt)
	return br, err
}

func (a PhysicalMaxLevel) Readable() bool   { return true }
func (a PhysicalMaxLevel) Writable() bool   { return false }
func (a PhysicalMaxLevel) Reportable() bool { return false }
func (a PhysicalMaxLevel) SceneIndex() int  { return -1 }

func (a PhysicalMaxLevel) String() string {
	return zcl.Sprintf("%v", zcl.Zu8(a))
}

// BallastStatus is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the activity status of the ballast functions. Where a
// function is active, the corresponding bit is 1. Where a function is
// not active, the corresponding bit is 0. This means that bit 0 with
// a value of 0 means the ballast is operational and bit 1 with a
// value of 0 that the lamp(s) is/are in their socket(s)
type BallastStatus zcl.Zbmp8

const BallastStatusAttr zcl.AttrID = 2

func (a BallastStatus) ID() zcl.AttrID         { return BallastStatusAttr }
func (a BallastStatus) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *BallastStatus) Value() *BallastStatus { return a }
func (a BallastStatus) MarshalZcl() ([]byte, error) {
	return zcl.Zbmp8(a).MarshalZcl()
}
func (a *BallastStatus) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zbmp8)
	br, err := nt.UnmarshalZcl(b)
	*a = BallastStatus(*nt)
	return br, err
}

func (a BallastStatus) Readable() bool   { return true }
func (a BallastStatus) Writable() bool   { return false }
func (a BallastStatus) Reportable() bool { return false }
func (a BallastStatus) SceneIndex() int  { return -1 }

func (a BallastStatus) String() string {
	var bstr []string
	if a.IsNonOperational() {
		bstr = append(bstr, "Non-operational")
	}
	if a.IsLampNotInSocket() {
		bstr = append(bstr, "Lamp not in socket")
	}
	return zcl.StrJoin(bstr, ", ")
}

func (a BallastStatus) IsNonOperational() bool {
	return zcl.BitmapTest([]byte(a), 0)
}
func (a *BallastStatus) SetNonOperational(b bool) {
	*a = BallastStatus(zcl.BitmapSet([]byte(*a), 0, b))
}

func (a BallastStatus) IsLampNotInSocket() bool {
	return zcl.BitmapTest([]byte(a), 1)
}
func (a *BallastStatus) SetLampNotInSocket(b bool) {
	*a = BallastStatus(zcl.BitmapSet([]byte(*a), 1, b))
}

// MinLevel is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the minimum light level the ballast is permitted to use.
// It is specified in the range 0x01 to 0xfe, and specifies the light
// output of the ballast according to the dimming light curve. The value
// is both greater than or equal to PhysicalMinLevel and less than or equal
// to MaxLevel
type MinLevel zcl.Zu8

const MinLevelAttr zcl.AttrID = 16

func (a MinLevel) ID() zcl.AttrID         { return MinLevelAttr }
func (a MinLevel) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *MinLevel) Value() *MinLevel      { return a }
func (a MinLevel) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *MinLevel) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = MinLevel(*nt)
	return br, err
}

func (a MinLevel) Readable() bool   { return true }
func (a MinLevel) Writable() bool   { return true }
func (a MinLevel) Reportable() bool { return false }
func (a MinLevel) SceneIndex() int  { return -1 }

func (a MinLevel) String() string {
	return zcl.Sprintf("%v", zcl.Zu8(a))
}

// MaxLevel is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the maximum light level the ballast is permitted to use.
// It is specified in the range 0x01 to 0xfe, and specifies the light
// output of the ballast according to the dimming light curve. The value
// is both less than or equal to PhysicalMaxLevel and greater than or equal
// to MinLevel
type MaxLevel zcl.Zu8

const MaxLevelAttr zcl.AttrID = 17

func (a MaxLevel) ID() zcl.AttrID         { return MaxLevelAttr }
func (a MaxLevel) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *MaxLevel) Value() *MaxLevel      { return a }
func (a MaxLevel) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *MaxLevel) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = MaxLevel(*nt)
	return br, err
}

func (a MaxLevel) Readable() bool   { return true }
func (a MaxLevel) Writable() bool   { return true }
func (a MaxLevel) Reportable() bool { return false }
func (a MaxLevel) SceneIndex() int  { return -1 }

func (a MaxLevel) String() string {
	return zcl.Sprintf("%v", zcl.Zu8(a))
}

// PowerOnLevel is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the light level to which the ballast will go when power
// is applied (e.g., when mains power is re-established after a power
// failure). It can have a value between 0x00 and 0xfe to set it to
// a specific light level, according to the dimming light curve, or
// 0xff to set it to the value it was before the power failure
type PowerOnLevel zcl.Zu8

const PowerOnLevelAttr zcl.AttrID = 18

func (a PowerOnLevel) ID() zcl.AttrID         { return PowerOnLevelAttr }
func (a PowerOnLevel) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *PowerOnLevel) Value() *PowerOnLevel  { return a }
func (a PowerOnLevel) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *PowerOnLevel) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = PowerOnLevel(*nt)
	return br, err
}

func (a PowerOnLevel) Readable() bool   { return true }
func (a PowerOnLevel) Writable() bool   { return true }
func (a PowerOnLevel) Reportable() bool { return false }
func (a PowerOnLevel) SceneIndex() int  { return -1 }

func (a PowerOnLevel) String() string {
	return zcl.Sprintf("%v", zcl.Zu8(a))
}

// PowerOnFadeTime is an autogenerated attribute in the BallastConfiguration cluster
// Is the length of time, in tenths of a second, that the ballast takes to
// move to the light level specified in PowerOnLevel when power is applied
// (e.g., when mains power is re-established after a power failure).
type PowerOnFadeTime zcl.Zu16

const PowerOnFadeTimeAttr zcl.AttrID = 19

func (a PowerOnFadeTime) ID() zcl.AttrID           { return PowerOnFadeTimeAttr }
func (a PowerOnFadeTime) Cluster() zcl.ClusterID   { return BallastConfigurationID }
func (a *PowerOnFadeTime) Value() *PowerOnFadeTime { return a }
func (a PowerOnFadeTime) MarshalZcl() ([]byte, error) {
	return zcl.Zu16(a).MarshalZcl()
}
func (a *PowerOnFadeTime) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu16)
	br, err := nt.UnmarshalZcl(b)
	*a = PowerOnFadeTime(*nt)
	return br, err
}

func (a PowerOnFadeTime) Readable() bool   { return true }
func (a PowerOnFadeTime) Writable() bool   { return true }
func (a PowerOnFadeTime) Reportable() bool { return false }
func (a PowerOnFadeTime) SceneIndex() int  { return -1 }

func (a PowerOnFadeTime) String() string {
	return zcl.Seconds.Format(float64(a) / 10)
}

// IntrinsicBallastFactor is an autogenerated attribute in the BallastConfiguration cluster
// It specifies, as a percentage, the ballast factor of the ballast/lamp
// combination, prior to any adjustment.
type IntrinsicBallastFactor zcl.Zu8

const IntrinsicBallastFactorAttr zcl.AttrID = 20

func (a IntrinsicBallastFactor) ID() zcl.AttrID                  { return IntrinsicBallastFactorAttr }
func (a IntrinsicBallastFactor) Cluster() zcl.ClusterID          { return BallastConfigurationID }
func (a *IntrinsicBallastFactor) Value() *IntrinsicBallastFactor { return a }
func (a IntrinsicBallastFactor) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *IntrinsicBallastFactor) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = IntrinsicBallastFactor(*nt)
	return br, err
}

func (a IntrinsicBallastFactor) Readable() bool   { return true }
func (a IntrinsicBallastFactor) Writable() bool   { return true }
func (a IntrinsicBallastFactor) Reportable() bool { return false }
func (a IntrinsicBallastFactor) SceneIndex() int  { return -1 }

func (a IntrinsicBallastFactor) String() string {
	return zcl.Percent.Format(float64(a))
}

// BallastFactorAdjustment is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the multiplication factor, as a percentage, to be applied
// to the configured light output of the lamps. A typical usage of this
// mechanism is to compensate for reduction in efficiency over the lifetime
// of a lamp. The light output is given by
// Actual light output = configured light output x BallastFactorAdjustment / 100%
// The range for this attribute is manufacturer dependent
type BallastFactorAdjustment zcl.Zu8

const BallastFactorAdjustmentAttr zcl.AttrID = 21

func (a BallastFactorAdjustment) ID() zcl.AttrID                   { return BallastFactorAdjustmentAttr }
func (a BallastFactorAdjustment) Cluster() zcl.ClusterID           { return BallastConfigurationID }
func (a *BallastFactorAdjustment) Value() *BallastFactorAdjustment { return a }
func (a BallastFactorAdjustment) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *BallastFactorAdjustment) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = BallastFactorAdjustment(*nt)
	return br, err
}

func (a BallastFactorAdjustment) Readable() bool   { return true }
func (a BallastFactorAdjustment) Writable() bool   { return true }
func (a BallastFactorAdjustment) Reportable() bool { return false }
func (a BallastFactorAdjustment) SceneIndex() int  { return -1 }

func (a BallastFactorAdjustment) String() string {
	return zcl.Percent.Format(float64(a))
}

// LampQuantity is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the number of lamps connected to this ballast
type LampQuantity zcl.Zu8

const LampQuantityAttr zcl.AttrID = 32

func (a LampQuantity) ID() zcl.AttrID         { return LampQuantityAttr }
func (a LampQuantity) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *LampQuantity) Value() *LampQuantity  { return a }
func (a LampQuantity) MarshalZcl() ([]byte, error) {
	return zcl.Zu8(a).MarshalZcl()
}
func (a *LampQuantity) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu8)
	br, err := nt.UnmarshalZcl(b)
	*a = LampQuantity(*nt)
	return br, err
}

func (a LampQuantity) Readable() bool   { return true }
func (a LampQuantity) Writable() bool   { return false }
func (a LampQuantity) Reportable() bool { return false }
func (a LampQuantity) SceneIndex() int  { return -1 }

func (a LampQuantity) String() string {
	return zcl.Sprintf("%v", zcl.Zu8(a))
}

// LampType is an autogenerated attribute in the BallastConfiguration cluster
type LampType zcl.Zcstring

const LampTypeAttr zcl.AttrID = 48

func (a LampType) ID() zcl.AttrID         { return LampTypeAttr }
func (a LampType) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *LampType) Value() *LampType      { return a }
func (a LampType) MarshalZcl() ([]byte, error) {
	return zcl.Zcstring(a).MarshalZcl()
}
func (a *LampType) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zcstring)
	br, err := nt.UnmarshalZcl(b)
	*a = LampType(*nt)
	return br, err
}

func (a LampType) Readable() bool   { return true }
func (a LampType) Writable() bool   { return true }
func (a LampType) Reportable() bool { return false }
func (a LampType) SceneIndex() int  { return -1 }

func (a LampType) String() string {
	return zcl.Sprintf("%v", zcl.Zcstring(a))
}

// LampManufacturer is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the name of the manufacturer of the currently connected
// lamps.
type LampManufacturer zcl.Zcstring

const LampManufacturerAttr zcl.AttrID = 49

func (a LampManufacturer) ID() zcl.AttrID            { return LampManufacturerAttr }
func (a LampManufacturer) Cluster() zcl.ClusterID    { return BallastConfigurationID }
func (a *LampManufacturer) Value() *LampManufacturer { return a }
func (a LampManufacturer) MarshalZcl() ([]byte, error) {
	return zcl.Zcstring(a).MarshalZcl()
}
func (a *LampManufacturer) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zcstring)
	br, err := nt.UnmarshalZcl(b)
	*a = LampManufacturer(*nt)
	return br, err
}

func (a LampManufacturer) Readable() bool   { return true }
func (a LampManufacturer) Writable() bool   { return true }
func (a LampManufacturer) Reportable() bool { return false }
func (a LampManufacturer) SceneIndex() int  { return -1 }

func (a LampManufacturer) String() string {
	return zcl.Sprintf("%v", zcl.Zcstring(a))
}

// LampRatedHours is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the number of hours of use the lamps are rated for by
// the manufacturer
type LampRatedHours zcl.Zu24

const LampRatedHoursAttr zcl.AttrID = 50

func (a LampRatedHours) ID() zcl.AttrID          { return LampRatedHoursAttr }
func (a LampRatedHours) Cluster() zcl.ClusterID  { return BallastConfigurationID }
func (a *LampRatedHours) Value() *LampRatedHours { return a }
func (a LampRatedHours) MarshalZcl() ([]byte, error) {
	return zcl.Zu24(a).MarshalZcl()
}
func (a *LampRatedHours) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu24)
	br, err := nt.UnmarshalZcl(b)
	*a = LampRatedHours(*nt)
	return br, err
}

func (a LampRatedHours) Readable() bool   { return true }
func (a LampRatedHours) Writable() bool   { return true }
func (a LampRatedHours) Reportable() bool { return false }
func (a LampRatedHours) SceneIndex() int  { return -1 }

func (a LampRatedHours) String() string {
	return zcl.Sprintf("%v", zcl.Zu24(a))
}

// LampBurnHours is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the length of time, in hours, the currently connected
// lamps have been operated, cumulative since the last re-lamping. Burn
// hours are not accumulated if the lamps are off and are reset to 0
// when a lamp is changed
type LampBurnHours zcl.Zu24

const LampBurnHoursAttr zcl.AttrID = 51

func (a LampBurnHours) ID() zcl.AttrID         { return LampBurnHoursAttr }
func (a LampBurnHours) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *LampBurnHours) Value() *LampBurnHours { return a }
func (a LampBurnHours) MarshalZcl() ([]byte, error) {
	return zcl.Zu24(a).MarshalZcl()
}
func (a *LampBurnHours) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu24)
	br, err := nt.UnmarshalZcl(b)
	*a = LampBurnHours(*nt)
	return br, err
}

func (a LampBurnHours) Readable() bool   { return true }
func (a LampBurnHours) Writable() bool   { return true }
func (a LampBurnHours) Reportable() bool { return false }
func (a LampBurnHours) SceneIndex() int  { return -1 }

func (a LampBurnHours) String() string {
	return zcl.Sprintf("%v", zcl.Zu24(a))
}

// LampAlarmMode is an autogenerated attribute in the BallastConfiguration cluster
// It specifies which attributes can cause an alarm notification to be
// generated
type LampAlarmMode zcl.Zbmp8

const LampAlarmModeAttr zcl.AttrID = 52

func (a LampAlarmMode) ID() zcl.AttrID         { return LampAlarmModeAttr }
func (a LampAlarmMode) Cluster() zcl.ClusterID { return BallastConfigurationID }
func (a *LampAlarmMode) Value() *LampAlarmMode { return a }
func (a LampAlarmMode) MarshalZcl() ([]byte, error) {
	return zcl.Zbmp8(a).MarshalZcl()
}
func (a *LampAlarmMode) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zbmp8)
	br, err := nt.UnmarshalZcl(b)
	*a = LampAlarmMode(*nt)
	return br, err
}

func (a LampAlarmMode) Readable() bool   { return true }
func (a LampAlarmMode) Writable() bool   { return true }
func (a LampAlarmMode) Reportable() bool { return false }
func (a LampAlarmMode) SceneIndex() int  { return -1 }

func (a LampAlarmMode) String() string {
	var bstr []string
	if a.IsLampBurnHours() {
		bstr = append(bstr, "Lamp Burn Hours")
	}
	return zcl.StrJoin(bstr, ", ")
}

func (a LampAlarmMode) IsLampBurnHours() bool {
	return zcl.BitmapTest([]byte(a), 0)
}
func (a *LampAlarmMode) SetLampBurnHours(b bool) {
	*a = LampAlarmMode(zcl.BitmapSet([]byte(*a), 0, b))
}

// LampBurnHoursTripPoint is an autogenerated attribute in the BallastConfiguration cluster
// It specifies the number of hours the LampBurnHours attribute can
// reach before an alarm is generated
type LampBurnHoursTripPoint zcl.Zu24

const LampBurnHoursTripPointAttr zcl.AttrID = 53

func (a LampBurnHoursTripPoint) ID() zcl.AttrID                  { return LampBurnHoursTripPointAttr }
func (a LampBurnHoursTripPoint) Cluster() zcl.ClusterID          { return BallastConfigurationID }
func (a *LampBurnHoursTripPoint) Value() *LampBurnHoursTripPoint { return a }
func (a LampBurnHoursTripPoint) MarshalZcl() ([]byte, error) {
	return zcl.Zu24(a).MarshalZcl()
}
func (a *LampBurnHoursTripPoint) UnmarshalZcl(b []byte) ([]byte, error) {
	nt := new(zcl.Zu24)
	br, err := nt.UnmarshalZcl(b)
	*a = LampBurnHoursTripPoint(*nt)
	return br, err
}

func (a LampBurnHoursTripPoint) Readable() bool   { return true }
func (a LampBurnHoursTripPoint) Writable() bool   { return true }
func (a LampBurnHoursTripPoint) Reportable() bool { return false }
func (a LampBurnHoursTripPoint) SceneIndex() int  { return -1 }

func (a LampBurnHoursTripPoint) String() string {
	return zcl.Sprintf("%v", zcl.Zu24(a))
}
